version: 2
run:
  tests: true

linters:
  enable:
    - gocritic
    - errorlint
    - gomodguard

linters-settings:
  gomodguard:
    blocked:
      modules:
        - github.com/pkg/errors:
            recommendations:
              - errors
            reason: "Use standard library errors package"
        - io/ioutil:
            recommendations:
              - io
              - os
            reason: "Deprecated since Go 1.16"
      local_replace_directives: false

issues:
  exclude:
    - composite
